/* global jQuery:false */
/* global FRANK_JEWELRY_STORE_STORAGE:false */
/* global TRX_ADDONS_STORAGE:false */

jQuery(document).on('action.add_googlemap_styles', frank_jewelry_store_trx_addons_add_googlemap_styles);
jQuery(document).on('action.init_shortcodes', frank_jewelry_store_trx_addons_init);
jQuery(document).on('action.init_hidden_elements', frank_jewelry_store_trx_addons_init);

// Add theme specific styles to the Google map
function frank_jewelry_store_trx_addons_add_googlemap_styles(e) {
	TRX_ADDONS_STORAGE['googlemap_styles']['dark'] = [{"featureType":"all","elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#333333"},{"lightness":40}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#ffffff"},{"lightness":16}]},{"featureType":"all","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#fefefe"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#fefefe"},{"lightness":17},{"weight":1.2}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"lightness":20},{"color":"#13162b"}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#13162b"},{"lightness":21}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#5fc6ca"},{"lightness":21}]},{"featureType":"road","elementType":"all","stylers":[{"visibility":"simplified"},{"color":"#cccdd2"}]},{"featureType":"road","elementType":"geometry","stylers":[{"color":"#13162b"}]},{"featureType":"road","elementType":"geometry.fill","stylers":[{"color":"#ff0000"}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#13162b"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#ffffff"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#13162b"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#13162b"},{"lightness":16}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#13162b"},{"lightness":19}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#f4f9fc"},{"lightness":17}]}];
    TRX_ADDONS_STORAGE['googlemap_styles']['new'] = [{ "featureType": "all", "elementType": "labels.text.fill", "stylers": [{ "saturation": 36}, { "color": "#000000"}, { "lightness": 40}]}, { "featureType": "all", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "on"}, { "color": "#000000"}, { "lightness": 16}]}, { "featureType": "all", "elementType": "labels.icon", "stylers": [{ "visibility": "off"}]}, { "featureType": "administrative", "elementType": "geometry.fill", "stylers": [{ "color": "#000000"}, { "lightness": 20}]}, { "featureType": "administrative", "elementType": "geometry.stroke", "stylers": [{ "color": "#000000"}, { "lightness": 17}, { "weight": 1.2}]}, { "featureType": "administrative.locality", "elementType": "labels.text", "stylers": [{ "visibility": "simplified"}, { "lightness": "15"}, { "hue": "#ff6000"}]}, { "featureType": "landscape", "elementType": "geometry", "stylers": [{ "color": "#000000"}, { "lightness": 20}]}, { "featureType": "poi", "elementType": "geometry", "stylers": [{ "color": "#000000"}, { "lightness": 21}]}, { "featureType": "poi", "elementType": "labels.text", "stylers": [{ "visibility": "off"}]}, { "featureType": "road.highway", "elementType": "geometry.fill", "stylers": [{ "color": "#000000"}, { "lightness": 17}, { "visibility": "off"}]}, { "featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [{ "color": "#000000"}, { "lightness": 29}, { "weight": 0.2}, { "visibility": "on"}]}, { "featureType": "road.highway", "elementType": "labels.text", "stylers": [{ "visibility": "off"}]}, { "featureType": "road.arterial", "elementType": "geometry", "stylers": [{ "color": "#000000"}, { "lightness": 18}]}, { "featureType": "road.local", "elementType": "geometry", "stylers": [{ "color": "#000000"}, { "lightness": 16}]}, { "featureType": "transit", "elementType": "geometry", "stylers": [{ "color": "#000000"}, { "lightness": 19}]}, { "featureType": "water", "elementType": "geometry", "stylers": [{ "color": "#000000"}, { "lightness": 17}]}];
}


function frank_jewelry_store_trx_addons_init(e, container) {
	"use strict";
	if (arguments.length < 2) var container = jQuery('body');
	if (container===undefined || container.length === undefined || container.length == 0) return;

	container.find('.sc_countdown_item canvas:not(.inited)').addClass('inited').attr('data-color', FRANK_JEWELRY_STORE_STORAGE['alter_link_color']);
}